### ISSUE TITLE
Suggestion: standardize title

### ISSUE THREAD

**Issue by lee2sman** [lee2sman/class-playlist#21]
Hi, right now the titles are just copypasta but we can make this a more beautiful list with a standard

**Comment by stuffedmeow** [comment]
How about:
Song title | Artist

**Comment by lee2sman** [comment]
what about album? should that be included?

**Comment by stuffedmeow** [comment]
Sometimes the addition is already a whole album, what then?

**Comment by bmento** [comment]
Organize by genre?

**Comment by Mike01999** [comment]
Maybe do it by alphabetical, genre and artist order.

**Comment by Supermonkey56789** [comment]
Make it date order on oldest to newest song

**Comment by MacSmitty8** [comment]
Add a genre section, THEN sort it through alphabetical and other orders.

**Comment by melissandrej** [comment]
I'll be making a separate playlist with just the alphabetical order.

**Comment by Supermonkey56789** [comment]
I'll make a separate playlist in date order

**Comment by lee2sman** [comment]
First way is a bit clearer.
