### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by scotiam** [lee2sman/class-playlist#22]
Some of the links (like the first one) are short links, while others are the full link.  I think we should use the short links for them all.
(short= youtu.be)

**Comment by YaredGl** [comment]
[Hyperlinks](https://www.youtube.com/watch?v=xvFZjo5PgG0)

**Comment by scotiam** [comment]
[Short Hyperlink](https://youtu.be/Ub3UAK_KeNI)

**Comment by cpetrella-sketch** [comment]
Mine were hyperlinks, they just didn't copy over correctly and I didn't know how to fix them.
