### ISSUE TITLE
Personal Playlists

### ISSUE THREAD

**Issue by stuffedmeow** [lee2sman/class-playlist#23]
Should we all have our own personal playlists? ie) Michael has one, or should it just be a collective one?

**Comment by YaredGl** [comment]
Collective, I [believe](https://www.youtube.com/watch?v=xvFZjo5PgG0)

**Comment by stuffedmeow** [comment]
If we did each have personal playlists, I still believe we should follow the same format of organizing (standardized titles, order in which things are listed, etc).

**Comment by stuffedmeow** [comment]
In that case, do y'all think there should be no personal playlists at all then?

**Comment by lee2sman** [comment]
hahah, i'd do a personal playlist too but if we're the only two that'd contribute, and @Mike01999 ....not sure
