### ISSUE TITLE
Add a "How To Contribute a Track" and Playlist Descriptions to the README.md

### ISSUE THREAD

**Issue by lee2sman** [lee2sman/class-playlist#34]
Our README.md is small. 

It would be helpful to add 2 new sections:
- A playlist section listing and linking to our various playlists (and describing them if necessary)
- A Contributing section on how to add a new track to the playlist(s) (standard formating, etc)

Anything else needed?

**Comment by lee2sman** [comment]
Can anyone work on this?

**Comment by Nevarious** [comment]
I can do this

**Comment by lee2sman** [comment]
Updated in #39
