### ISSUE TITLE
Create separate playlists for each genre instead of grouping them in one.

### ISSUE THREAD

**Issue by Doc-Chocula** [lee2sman/class-playlist#49]

**Comment by lee2sman** [comment]
Well, we've already got a large number of playlists already and the genre (which is really mood here) lists are already pretty short. This might make it hard to work on this project going forward with that many separate playlist files.

 Something that would be more immediately useful, can you check out #5 ? Or feel free to open another issue. I'm going to leave this one up for a bit and see if there's more feedback from others.
