### ISSUE TITLE
Links don't currently work to open up a new page

### ISSUE THREAD

**Issue by lee2sman** [lee2sman/class-playlist#5]
The way this project was started is a little bit mistaken. The links are just text, but they won't function as links right now. You should probably turn them into hyperlinks.

**Comment by lee2sman** [comment]
Links in Markdown are done like this:

```
Here is a [link](https://www.website.com)
```

**Comment by lee2sman** [comment]
Update: I'm wrong! Links in GitHub automatically do link!

**Comment by pogerbrin** [comment]
turn playlist submissions into hyperlinks

**Comment by lee2sman** [comment]
Hi, we need someone to take our links and format them correctly! Who can do this? 

currently, links look like this:
```
My cool music track http://www.youtube.com/rchoXE293Eo
```

We need to change them to markdown like this:
```
[My cool music track](http://www.youtube.com/rchoXE293Eo)
```
